import { PlanetData } from './types';

export const planets: PlanetData[] = [
  {
    id: 'sun',
    name: 'Sun',
    type: 'G-type main-sequence star',
    diameter: '1,391,000 km',
    gravity: '274 m/s²',
    moons: 0,
    distanceFromSun: '0 km',
    orbitalPeriod: '—',
    atmosphere: 'Hydrogen (73%), Helium (25%)',
    temperature: '5,500°C (surface)',
    color: '#ff6b00',
    emissive: '#ff4400',
    size: 8,
    orbitRadius: 0,
    orbitalSpeed: 0,
    axialTilt: 7.25,
    rotationSpeed: 0.004,
    funFacts: [
      'The Sun contains 99.86% of all mass in our solar system',
      'Light from the Sun takes about 8 minutes and 20 seconds to reach Earth',
      'The Sun\'s core temperature is about 15 million degrees Celsius',
    ],
    missions: ['Parker Solar Probe', 'Solar Orbiter', 'SOHO'],
    hasRing: false,
    hasClouds: false,
    hasAtmosphere: true,
    hasMoon: false,
    description: 'The Sun is a yellow dwarf star at the center of our solar system, a nearly perfect sphere of hot plasma that has been shining for 4.6 billion years.',
    textureMap: '/textures/2k_sun.jpg',
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'Terrestrial planet',
    diameter: '4,879 km',
    gravity: '3.7 m/s²',
    moons: 0,
    distanceFromSun: '57.9 million km',
    orbitalPeriod: '88 days',
    atmosphere: 'Extremely thin (exosphere)',
    temperature: '-180°C to 430°C',
    color: '#a5a5a5',
    emissive: '#555555',
    size: 0.45,
    orbitRadius: 14,
    orbitalSpeed: 4.15,
    axialTilt: 0.034,
    rotationSpeed: 0.017,
    funFacts: [
      'A year on Mercury is just 88 Earth days',
      'Mercury has no atmosphere to retain heat, causing extreme temperature swings',
      'Despite being closest to the Sun, Venus is actually hotter than Mercury',
    ],
    missions: ['Mariner 10', 'MESSENGER', 'BepiColombo'],
    hasRing: false,
    hasClouds: false,
    hasAtmosphere: false,
    hasMoon: false,
    description: 'Mercury is the smallest planet in our solar system and closest to the Sun, a world of extremes with scorching days and freezing nights.',
    textureMap: '/textures/2k_mercury.jpg',
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'Terrestrial planet',
    diameter: '12,104 km',
    gravity: '8.87 m/s²',
    moons: 0,
    distanceFromSun: '108.2 million km',
    orbitalPeriod: '225 days',
    atmosphere: 'Carbon dioxide (96%), Nitrogen (3.5%)',
    temperature: '462°C (average)',
    color: '#e8cda0',
    emissive: '#c4944a',
    size: 0.95,
    orbitRadius: 20,
    orbitalSpeed: 3.25,
    axialTilt: 177.4,
    rotationSpeed: -0.004,
    funFacts: [
      'Venus rotates backwards compared to most planets',
      'A day on Venus is longer than its year',
      'Venus is often called Earth\'s "sister planet" due to similar size',
    ],
    missions: ['Venera program', 'Magellan', 'Venus Express', 'Akatsuki'],
    hasRing: false,
    hasClouds: true,
    hasAtmosphere: true,
    hasMoon: false,
    description: 'Venus is the hottest planet in our solar system, shrouded in thick clouds of sulfuric acid that trap heat in a runaway greenhouse effect.',
    textureMap: '/textures/2k_venus.jpg',
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'Terrestrial planet',
    diameter: '12,756 km',
    gravity: '9.81 m/s²',
    moons: 1,
    distanceFromSun: '149.6 million km',
    orbitalPeriod: '365.25 days',
    atmosphere: 'Nitrogen (78%), Oxygen (21%)',
    temperature: '-89°C to 57°C',
    color: '#4b7fbf',
    emissive: '#2d4a7a',
    size: 1.0,
    orbitRadius: 28,
    orbitalSpeed: 2.98,
    axialTilt: 23.44,
    rotationSpeed: 0.01,
    funFacts: [
      'Earth is the only known planet to support life',
      'About 71% of Earth\'s surface is covered by water',
      'Earth\'s atmosphere protects us from harmful solar radiation',
    ],
    missions: ['ISS', 'Hubble Space Telescope', 'JWST', ' countless satellites'],
    hasRing: false,
    hasClouds: true,
    hasAtmosphere: true,
    hasMoon: true,
    description: 'Earth is our home, the third planet from the Sun and the only world known to harbor life, with a unique blend of liquid water, atmosphere, and magnetic field.',
    textureMap: '/textures/2k_earth_atmos_2048.jpg',
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'Terrestrial planet',
    diameter: '6,792 km',
    gravity: '3.72 m/s²',
    moons: 2,
    distanceFromSun: '227.9 million km',
    orbitalPeriod: '687 days',
    atmosphere: 'Carbon dioxide (95%), Argon (2%)',
    temperature: '-140°C to 20°C',
    color: '#c1440e',
    emissive: '#8a2c0a',
    size: 0.6,
    orbitRadius: 38,
    orbitalSpeed: 2.41,
    axialTilt: 25.19,
    rotationSpeed: 0.0097,
    funFacts: [
      'Mars has the tallest mountain in the solar system, Olympus Mons at 21.9 km',
      'Mars has evidence of ancient river valleys and possibly an ocean',
      'A day on Mars (a "sol") is only 40 minutes longer than an Earth day',
    ],
    missions: ['Perseverance', 'Curiosity', 'Ingenuity', 'Mars Reconnaissance Orbiter'],
    hasRing: false,
    hasClouds: true,
    hasAtmosphere: true,
    hasMoon: true,
    description: 'Mars, the Red Planet, is a dusty cold desert world with a thin atmosphere, home to the largest volcano in the solar system and ongoing robotic exploration.',
    textureMap: '/textures/2k_mars.jpg',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'Gas giant',
    diameter: '142,984 km',
    gravity: '24.79 m/s²',
    moons: 95,
    distanceFromSun: '778.5 million km',
    orbitalPeriod: '11.86 years',
    atmosphere: 'Hydrogen (90%), Helium (10%)',
    temperature: '-110°C (cloud top)',
    color: '#c88b3a',
    emissive: '#8a5c1e',
    size: 2.8,
    orbitRadius: 58,
    orbitalSpeed: 1.31,
    axialTilt: 3.13,
    rotationSpeed: 0.04,
    funFacts: [
      'Jupiter is the largest planet in our solar system',
      'The Great Red Spot is a storm larger than Earth that has raged for centuries',
      'Jupiter has a faint ring system made of dust',
    ],
    missions: ['Juno', 'Galileo', 'Voyager 1 & 2', 'Cassini'],
    hasRing: true,
    hasClouds: true,
    hasAtmosphere: true,
    hasMoon: true,
    description: 'Jupiter is a massive gas giant, the largest planet in our solar system, famous for its colorful bands and the iconic Great Red Spot storm.',
    textureMap: '/textures/2k_jupiter.jpg',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'Gas giant',
    diameter: '120,536 km',
    gravity: '10.44 m/s²',
    moons: 146,
    distanceFromSun: '1.43 billion km',
    orbitalPeriod: '29.46 years',
    atmosphere: 'Hydrogen (96%), Helium (3%)',
    temperature: '-140°C (cloud top)',
    color: '#e8d5a3',
    emissive: '#a89060',
    size: 2.4,
    orbitRadius: 80,
    orbitalSpeed: 0.97,
    axialTilt: 26.73,
    rotationSpeed: 0.036,
    funFacts: [
      'Saturn\'s ring system spans up to 282,000 km but is only 10 meters thick',
      'Saturn is so light it would float in water (if you could find a big enough pool)',
      'Saturn has at least 146 known moons, more than any other planet',
    ],
    missions: ['Cassini-Huygens', 'Voyager 1 & 2', 'Pioneer 11'],
    hasRing: true,
    hasClouds: true,
    hasAtmosphere: true,
    hasMoon: true,
    description: 'Saturn is a stunning gas giant encircled by magnificent rings made of ice and rock, the most visually spectacular planet in our solar system.',
    textureMap: '/textures/2k_saturn.jpg',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'Ice giant',
    diameter: '51,118 km',
    gravity: '8.69 m/s²',
    moons: 27,
    distanceFromSun: '2.87 billion km',
    orbitalPeriod: '84.01 years',
    atmosphere: 'Hydrogen (83%), Helium (15%), Methane (2%)',
    temperature: '-195°C',
    color: '#7ec8e3',
    emissive: '#4a8caa',
    size: 1.6,
    orbitRadius: 105,
    orbitalSpeed: 0.68,
    axialTilt: 97.77,
    rotationSpeed: -0.02,
    funFacts: [
      'Uranus rotates on its side, with an axial tilt of 98 degrees',
      'Methane in its atmosphere gives Uranus its blue-green color',
      'Uranus was the first planet discovered with a telescope in 1781',
    ],
    missions: ['Voyager 2 (only flyby)'],
    hasRing: true,
    hasClouds: true,
    hasAtmosphere: true,
    hasMoon: true,
    description: 'Uranus is a tilted ice giant that rotates on its side, with a blue-green atmosphere and a pale ring system, discovered just 250 years ago.',
    textureMap: '/textures/2k_uranus.jpg',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'Ice giant',
    diameter: '49,528 km',
    gravity: '11.15 m/s²',
    moons: 16,
    distanceFromSun: '4.50 billion km',
    orbitalPeriod: '164.8 years',
    atmosphere: 'Hydrogen (80%), Helium (19%), Methane (1.5%)',
    temperature: '-200°C',
    color: '#3b5ce7',
    emissive: '#1a2d8a',
    size: 1.5,
    orbitRadius: 132,
    orbitalSpeed: 0.54,
    axialTilt: 28.32,
    rotationSpeed: -0.022,
    funFacts: [
      'Neptune has the strongest winds of any planet, reaching 2,100 km/h',
      'Neptune was the first planet predicted mathematically before being observed',
      'Neptune takes 165 Earth years to complete one orbit around the Sun',
    ],
    missions: ['Voyager 2 (only flyby)'],
    hasRing: true,
    hasClouds: true,
    hasAtmosphere: true,
    hasMoon: true,
    description: 'Neptune is a dark cold ice giant at the edge of our solar system, whipped by the fastest winds in the solar system and a vivid blue world.',
    textureMap: '/textures/2k_neptune.jpg',
  },
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'Dwarf planet',
    diameter: '2,377 km',
    gravity: '0.62 m/s²',
    moons: 5,
    distanceFromSun: '5.91 billion km',
    orbitalPeriod: '248 years',
    atmosphere: 'Thin nitrogen atmosphere',
    temperature: '-230°C',
    color: '#d4c4a8',
    emissive: '#8a7a60',
    size: 0.3,
    orbitRadius: 145,
    orbitalSpeed: 0.25,
    axialTilt: 122.5,
    rotationSpeed: -0.01,
    funFacts: [
      'Pluto was reclassified as a dwarf planet in 2006',
      'Pluto has a heart-shaped glacier called Sputnik Planitia',
      'Pluto\'s largest moon Charon is so large they orbit each other',
    ],
    missions: ['New Horizons (2015 flyby)'],
    hasRing: false,
    hasClouds: false,
    hasAtmosphere: true,
    hasMoon: true,
    description: 'Pluto is a complex dwarf planet at the edge of our solar system, with icy mountains, nitrogen glaciers, and a thin atmosphere discovered by New Horizons.',
    textureMap: '/textures/2k_pluto.jpg',
  },
  {
    id: 'ceres',
    name: 'Ceres',
    type: 'Dwarf planet',
    diameter: '939 km',
    gravity: '0.28 m/s²',
    moons: 0,
    distanceFromSun: '414 million km',
    orbitalPeriod: '4.6 years',
    atmosphere: 'None (thin exosphere)',
    temperature: '-105°C',
    color: '#9a8a7a',
    emissive: '#5a4a3a',
    size: 0.2,
    orbitRadius: 46,
    orbitalSpeed: 1.5,
    axialTilt: 4,
    rotationSpeed: 0.005,
    funFacts: [
      'Ceres is the largest object in the asteroid belt',
      'Ceres may have a subsurface ocean of liquid water',
      'Ceres was originally classified as a planet, then an asteroid, now a dwarf planet',
    ],
    missions: ['Dawn (orbiter)'],
    hasRing: false,
    hasClouds: false,
    hasAtmosphere: false,
    hasMoon: false,
    description: 'Ceres is the largest object in the asteroid belt, a dwarf planet with possible subsurface water and a bright salt deposit called Occator Crater.',
    textureMap: '/textures/2k_ceres.jpg',
  },
  {
    id: 'eris',
    name: 'Eris',
    type: 'Dwarf planet',
    diameter: '2,326 km',
    gravity: '0.82 m/s²',
    moons: 1,
    distanceFromSun: '10.12 billion km',
    orbitalPeriod: '559 years',
    atmosphere: 'Methane ice haze',
    temperature: '-243°C',
    color: '#b0a8a0',
    emissive: '#6a6058',
    size: 0.25,
    orbitRadius: 175,
    orbitalSpeed: 0.18,
    axialTilt: 78,
    rotationSpeed: -0.008,
    funFacts: [
      'Eris is the most massive known dwarf planet in the solar system',
      'Eris\'s discovery triggered the reclassification of Pluto',
      'Eris has a small moon named Dysnomia',
    ],
    missions: ['None yet'],
    hasRing: false,
    hasClouds: false,
    hasAtmosphere: false,
    hasMoon: true,
    description: 'Eris is the most massive dwarf planet, located in the scattered disc beyond Neptune, whose discovery reshaped our understanding of the solar system.',
    textureMap: '/textures/2k_eris.jpg',
  },
  {
    id: 'makemake',
    name: 'Makemake',
    type: 'Dwarf planet',
    diameter: '1,430 km',
    gravity: '0.5 m/s²',
    moons: 1,
    distanceFromSun: '6.85 billion km',
    orbitalPeriod: '310 years',
    atmosphere: 'Methane and nitrogen',
    temperature: '-239°C',
    color: '#c8b8a8',
    emissive: '#7a6a58',
    size: 0.2,
    orbitRadius: 160,
    orbitalSpeed: 0.2,
    axialTilt: 15,
    rotationSpeed: 0.005,
    funFacts: [
      'Makemake is named after the Rapa Nui god of creation',
      'Makemake was discovered in 2005 by Mike Brown and team',
      'Makemake has one known moon, MK2',
    ],
    missions: ['None yet'],
    hasRing: false,
    hasClouds: false,
    hasAtmosphere: false,
    hasMoon: true,
    description: 'Makemake is a dwarf planet in the Kuiper belt, a frozen world named after a creation deity from Easter Island mythology.',
    textureMap: '/textures/2k_makemake.jpg',
  },
  {
    id: 'haumea',
    name: 'Haumea',
    type: 'Dwarf planet',
    diameter: '1,632 km (elongated)',
    gravity: '0.4 m/s²',
    moons: 2,
    distanceFromSun: '6.45 billion km',
    orbitalPeriod: '285 years',
    atmosphere: 'None',
    temperature: '-241°C',
    color: '#b0b8b0',
    emissive: '#686e68',
    size: 0.18,
    orbitRadius: 150,
    orbitalSpeed: 0.22,
    axialTilt: 15,
    rotationSpeed: 0.1,
    funFacts: [
      'Haumea is shaped like an elongated rugby ball due to rapid rotation',
      'Haumea has a ring system! One of only a few dwarf planets with rings',
      'Haumea has two moons: Hi\'iaka and Namaka',
    ],
    missions: ['None yet'],
    hasRing: true,
    hasClouds: false,
    hasAtmosphere: false,
    hasMoon: true,
    description: 'Haumea is a strange elongated dwarf planet in the Kuiper belt, spinning so fast it stretched into an oval shape, with its own ring system.',
    textureMap: '/textures/2k_haumea.jpg',
  },
];

export const planetMap = new Map(planets.map((p) => [p.id, p]));

export const badges = [
  {
    id: 'first_explore',
    name: 'First Steps',
    description: 'Explored your first planet',
    icon: '🚀',
    requirement: 'Explore 1 planet',
  },
  {
    id: 'solar_explorer',
    name: 'Solar Explorer',
    description: 'Explored all 8 planets',
    icon: '🌌',
    requirement: 'Explore all 8 planets',
  },
  {
    id: 'quiz_master',
    name: 'Quiz Master',
    description: 'Completed all quizzes with 100% accuracy',
    icon: '🏆',
    requirement: 'Get 100% on all quizzes',
  },
  {
    id: 'streak_5',
    name: 'On Fire',
    description: '5-day learning streak',
    icon: '🔥',
    requirement: 'Maintain a 5-day streak',
  },
  {
    id: 'mercury_mastery',
    name: 'Mercury Apprentice',
    description: 'Mastered Mercury knowledge',
    icon: '☿️',
    requirement: 'Complete Mercury quiz with 80%+',
  },
  {
    id: 'venus_mastery',
    name: 'Venus Voyager',
    description: 'Mastered Venus knowledge',
    icon: '♀️',
    requirement: 'Complete Venus quiz with 80%+',
  },
  {
    id: 'earth_mastery',
    name: 'Earth Guardian',
    description: 'Mastered Earth knowledge',
    icon: '🌍',
    requirement: 'Complete Earth quiz with 80%+',
  },
  {
    id: 'mars_mastery',
    name: 'Mars Pioneer',
    description: 'Mastered Mars knowledge',
    icon: '♂️',
    requirement: 'Complete Mars quiz with 80%+',
  },
  {
    id: 'jupiter_mastery',
    name: 'Jupiter Giant',
    description: 'Mastered Jupiter knowledge',
    icon: '♃',
    requirement: 'Complete Jupiter quiz with 80%+',
  },
  {
    id: 'saturn_mastery',
    name: 'Saturn Ringmaster',
    description: 'Mastered Saturn knowledge',
    icon: '♄',
    requirement: 'Complete Saturn quiz with 80%+',
  },
  {
    id: 'uranus_mastery',
    name: 'Uranus Discoverer',
    description: 'Mastered Uranus knowledge',
    icon: '⛢',
    requirement: 'Complete Uranus quiz with 80%+',
  },
  {
    id: 'neptune_mastery',
    name: 'Neptune Navigator',
    description: 'Mastered Neptune knowledge',
    icon: '♆',
    requirement: 'Complete Neptune quiz with 80%+',
  },
  {
    id: 'speed_demon',
    name: 'Speed Demon',
    description: 'Completed a timed quiz with all correct',
    icon: '⚡',
    requirement: 'Perfect timed quiz',
  },
  {
    id: 'xp_1000',
    name: 'Rising Star',
    description: 'Earned 1000 XP',
    icon: '⭐',
    requirement: 'Earn 1000 XP',
  },
];